<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Demo Site_wpmenucart-icon-shopping-cart-0</name>
   <tag></tag>
   <elementGuidId>363eae5c-9d56-4627-b530-2cc97129c8d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.wpmenucart-icon-shopping-cart-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='wpmenucartli']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f24d47da-a4df-4f1d-90bc-51138648f6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpmenucart-icon-shopping-cart-0</value>
      <webElementGuid>9e05a949-87d8-41dd-afdf-fc3bfbabc5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpmenucartli&quot;)/a[@class=&quot;wpmenucart-contents&quot;]/i[@class=&quot;wpmenucart-icon-shopping-cart-0&quot;]</value>
      <webElementGuid>25107e64-afa9-4802-b704-97023018644a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='wpmenucartli']/a/i</value>
      <webElementGuid>4688e040-9b8c-4ba3-bc26-05016475f859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>88a2f3a1-d55d-4ac0-b7f2-d889ca7759b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
