<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Demo Site_wpmenucart-icon-shopping-cart-0</name>
   <tag></tag>
   <elementGuidId>3a652a0c-42c9-4f62-ac6c-6720e7b13fd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.wpmenucart-icon-shopping-cart-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='wpmenucartli']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9c32662a-46be-438a-89f1-37139f72cd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpmenucart-icon-shopping-cart-0</value>
      <webElementGuid>d2d97d75-13f2-4fe2-95af-dae181206bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpmenucartli&quot;)/a[@class=&quot;wpmenucart-contents&quot;]/i[@class=&quot;wpmenucart-icon-shopping-cart-0&quot;]</value>
      <webElementGuid>40352e27-ec17-4554-b203-fe724d67e5df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='wpmenucartli']/a/i</value>
      <webElementGuid>2a382703-ac6f-452b-b92b-20ab06a84a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>38fbfa94-c265-49dc-be87-7f2a18e1200e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
