<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billing_city</name>
   <tag></tag>
   <elementGuidId>01d21c0c-7e81-4dad-a7bd-730cf97bd009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b01c6b8-0588-4892-aeb0-1333db192e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62d9d43d-87f4-496b-9f1c-ff008832007e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>4c3e3992-a952-4181-ab11-902cbb29ad71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_city</value>
      <webElementGuid>24245667-157e-421c-864d-3c54ae171461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_city</value>
      <webElementGuid>c198506e-b27f-4c6d-bd58-7bb1d3b347a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-level2</value>
      <webElementGuid>33833164-6798-4931-a875-a7b01fa79e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_city&quot;)</value>
      <webElementGuid>09a40975-c4af-4afb-8481-e7f2d13b351d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_city']</value>
      <webElementGuid>301e90f0-bc52-43ab-b70e-39d7a4d85180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_city_field']/input</value>
      <webElementGuid>554b321f-cf2e-48e4-9676-33f6acf2e879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[9]/input</value>
      <webElementGuid>751de335-b569-4714-9fbe-b1d4d52a93f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_city' and @id = 'billing_city']</value>
      <webElementGuid>3dfcb122-d4b4-409b-96a4-fbea98803f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
