<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billing_first_name</name>
   <tag></tag>
   <elementGuidId>b7bda4cf-cf95-45b5-bebd-c295fdd941bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72f94f18-bc17-4e7e-8ffd-b4194c700b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f307b7a3-b44d-47a6-b4b7-2317504ebc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>a44e0beb-2ea8-4ced-a230-d26d42815470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_first_name</value>
      <webElementGuid>8bdee65f-b90d-42ba-ad7f-01e6288c79a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_first_name</value>
      <webElementGuid>ebf08138-94d5-4d37-820f-bc6e140724a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>48d9956c-814c-4245-ae59-001dda7b369d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_first_name&quot;)</value>
      <webElementGuid>6967efd6-dcb6-4163-be99-859444702e71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_first_name']</value>
      <webElementGuid>5f279081-b18d-43b3-bbb1-7d7cbf65df2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_first_name_field']/input</value>
      <webElementGuid>6d52061d-fc42-4c24-9e0b-3c8aa0eb111c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p/input</value>
      <webElementGuid>3f0d6c7c-eb4e-4ef0-b7b2-d348f490d26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_first_name' and @id = 'billing_first_name']</value>
      <webElementGuid>77010be6-5f39-4c4c-ae87-92a39808a31a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
